### ISSUE TITLE
Replace accents without typing html code

### ISSUE THREAD

**Issue by pprw** [Daniel-KM/Omeka-S-module-BulkEdit#1]
Would it be possible to allow replacing accents inside html media without using html code?

Right now, for replacing "été" by "automne", we have to enter "`&eacute;t&eacute;`" as "String to replace".

**Comment by Daniel-KM** [comment]
Yes, it's possible to check the two versions (because in some cases, the user uses utf-8 directly, sometime he uses entities. So I can add a checkbox to check all the variations.

**Comment by Daniel-KM** [comment]
Hi, I added this feature and another one. I think most of the points are fixed now.
