### ISSUE TITLE
Batch modifications broken

### ISSUE THREAD

**Issue by MickaelAHP** [Daniel-KM/Omeka-S-module-BulkEdit#2]
Batch modification only applies on the very first item (last created).

exemple : 
Lettre 1 test
Lettre 2 test
Lettre 3 test

I delete "test" on the three item, and only first will be impacted :

Lettre 1 
Lettre 2 test
Lettre 3 test

**Comment by Daniel-KM** [comment]
I think it's fixed. Can you recheck?
