### ISSUE TITLE
Trim property values Issue.

### ISSUE THREAD

**Issue by MickaelAHP** [Daniel-KM/Omeka-S-module-BulkEdit#3]
Trim property values feature return an error page ( screen attached).
![Trim Value](https://user-images.githubusercontent.com/48248876/60521853-3d854280-9ce8-11e9-969e-4c27ede7c3a9.PNG)

**Comment by Daniel-KM** [comment]
It's related to the version of mysql. I may add a check for that. regexp_replace is present in mysql 8+ (september 2016) and in mariadb 10.0.5 (november 2013), but, right, Omeka requires only mysql 5.5. So I'm going to add a check for the mysql version. 
To fix it, some user functions can be added (https://github.com/hholzgra/mysql-udf-regexp), but I don't think I'll fix it.

**Comment by Daniel-KM** [comment]
It will be fixed on Monday, and if an old mysql is used, it will be a simple trim (not full utf8).

**Comment by Daniel-KM** [comment]
I think it's fixed. Can you recheck?
