### ISSUE TITLE
Not working - Error

### ISSUE THREAD

**Issue by rafaeluriarte** [Daniel-KM/Omeka-S-module-BulkEdit#6]
While trying to use it, I got the following error (Omeka-s 2.1.0):

`2020-02-21T14:18:20+00:00 ERR (3): Doctrine\ORM\Query\QueryException: SELECT omeka_root.id FROM Omeka\Entity\Item omeka_root INNER JOIN Omeka\Entity\FulltextSearch omeka_0 WITH omeka_0.id = omeka_root.id AND omeka_0.resource = :omeka_3 WHERE MATCH(omeka_0.title, omeka_0.text) AGAINST (:omeka_2) > 0 GROUP BY omeka_root.id ORDER BY omeka_1 DESC, omeka_root.id ASC in /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:43
Stack trace:
#0 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(492): Doctrine\ORM\Query\QueryException::dqlError('SELECT omeka_ro...')
#1 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(716): Doctrine\ORM\Query\Parser->semanticalError('line 0, col 262...', Array)
#2 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(276): Doctrine\ORM\Query\Parser->processDeferredResultVariables()
#3 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(360): Doctrine\ORM\Query\Parser->getAST()
#4 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(286): Doctrine\ORM\Query\Parser->parse()
#5 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(298): Doctrine\ORM\Query->_parse()
#6 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(992): Doctrine\ORM\Query->_doExecute()
#7 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(947): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 3)
#8 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(774): Doctrine\ORM\AbstractQuery->execute(NULL, 3)
#9 /var/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(246): Doctrine\ORM\AbstractQuery->getScalarResult()
#10 /var/www/omeka-s/application/src/Api/Manager.php(221): Omeka\Api\Adapter\AbstractEntityAdapter->search(Object(Omeka\Api\Request))
#11 /var/www/omeka-s/application/src/Api/Manager.php(59): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#12 /var/www/omeka-s/application/src/Job/BatchUpdate.php(16): Omeka\Api\Manager->search('items', Array, Array)
#13 /var/www/omeka-s/application/src/Job/DispatchStrategy/Synchronous.php(34): Omeka\Job\BatchUpdate->perform()
#14 /var/www/omeka-s/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#15 /var/www/omeka-s/application/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
#16 {main}

Next Doctrine\ORM\Query\QueryException: [Semantical Error] line 0, col 262 near 'omeka_1 DESC,': Error: 'omeka_1' is not defined. in /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/QueryException.php:65
Stack trace:
#0 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(492): Doctrine\ORM\Query\QueryException::semanticalError('line 0, col 262...', Object(Doctrine\ORM\Query\QueryException))
#1 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(716): Doctrine\ORM\Query\Parser->semanticalError('line 0, col 262...', Array)
#2 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(276): Doctrine\ORM\Query\Parser->processDeferredResultVariables()
#3 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php(360): Doctrine\ORM\Query\Parser->getAST()
#4 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(286): Doctrine\ORM\Query\Parser->parse()
#5 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/Query.php(298): Doctrine\ORM\Query->_parse()
#6 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(992): Doctrine\ORM\Query->_doExecute()
#7 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(947): Doctrine\ORM\AbstractQuery->executeIgnoreQueryCache(NULL, 3)
#8 /var/www/omeka-s/vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php(774): Doctrine\ORM\AbstractQuery->execute(NULL, 3)
#9 /var/www/omeka-s/application/src/Api/Adapter/AbstractEntityAdapter.php(246): Doctrine\ORM\AbstractQuery->getScalarResult()
#10 /var/www/omeka-s/application/src/Api/Manager.php(221): Omeka\Api\Adapter\AbstractEntityAdapter->search(Object(Omeka\Api\Request))
#11 /var/www/omeka-s/application/src/Api/Manager.php(59): Omeka\Api\Manager->execute(Object(Omeka\Api\Request))
#12 /var/www/omeka-s/application/src/Job/BatchUpdate.php(16): Omeka\Api\Manager->search('items', Array, Array)
#13 /var/www/omeka-s/application/src/Job/DispatchStrategy/Synchronous.php(34): Omeka\Job\BatchUpdate->perform()
#14 /var/www/omeka-s/application/src/Job/Dispatcher.php(105): Omeka\Job\DispatchStrategy\Synchronous->send(Object(Omeka\Entity\Job))
#15 /var/www/omeka-s/application/data/scripts/perform-job.php(43): Omeka\Job\Dispatcher->send(Object(Omeka\Entity\Job), Object(Omeka\Job\DispatchStrategy\Synchronous))
#16 {main}
`

Here is the conf:

Status
Error
Started
February 21, 2020 at 3:26:46 PM GMT+1
Ended
February 21, 2020 at 3:26:46 PM GMT+1
Class
Omeka\Job\BatchUpdate
Owner
........
Args

{
    "resource": "items",
    "query": {
        "fulltext_search": "xxx",
        "resource-type": "item"
    },
    "data": {
        "bulkedit": {
            "cleaning": {
                "trim_values": "0",
                "deduplicate_values": "0"
            },
            "replace": {
                "from": "xxx",
                "to": "yyy",
                "mode": "raw",
                "remove": "0",
                "prepend": "",
                "append": "",
                "language": "",
                "language_clear": "0",
                "properties": null
            },
            "order_values": {
                "languages": "",
                "properties": null
            },
            "properties_visibility": {
                "visibility": "",
                "properties": null,
                "datatypes": null,
                "languages": "",
                "contains": ""
            },
            "displace": {
                "from": null,
                "to": "",
                "datatypes": null,
                "languages": "",
                "visibility": "",
                "contains": ""
            },
            "explode": {
                "properties": null,
                "separator": "",
                "contains": ""
            },
            "merge": {
                "properties": null
            },
            "convert": {
                "from": "",
                "to": "",
                "properties": null,
                "uri_label": ""
            },
            "media_html": {
                "from": "",
                "to": "",
                "mode": "raw",
                "remove": "0",
                "prepend": "",
                "append": ""
            }
        }
    },
    "data_remove": {
        "set_value_visibility": ""
    },
    "data_append": []
}

`
`

Any idea?

**Comment by Daniel-KM** [comment]
This is probably fixed in last version.
