### ISSUE TITLE
Bulk editing on boolean values fails

### ISSUE THREAD

**Issue by OyvindLGjesdal** [Daniel-KM/Omeka-S-module-BulkEdit#8]
Maybe related to https://github.com/Daniel-KM/Omeka-S-module-BulkExport/issues/8 in that there is a non string value used as input, where it expects a string.

Other relevant info: 
php 7.4
mariadb: 10.4
omeka-s version: 3.1.1
Data Type RDF version 3.3.4.1
BulkEdit version: 3.3.13.1
```
TypeError
trim() expects parameter 1 to be string, bool given

Details:

TypeError: trim() expects parameter 1 to be string, bool given in /media/omeka-s/modules/DataTypeRdf/src/DataType/Boolean.php:45
Stack trace:
#0 /media/omeka-s/modules/DataTypeRdf/src/DataType/Boolean.php(45): trim()
#1 /var/www/html/omeka-s/application/src/Api/Adapter/ValueHydrator.php(94): DataTypeRdf\DataType\Boolean->isValid()
#2 /var/www/html/omeka-s/application/src/Api/Adapter/AbstractResourceEntityAdapter.php(141):
...
```

**Comment by Daniel-KM** [comment]
Thanks, in fact it is an issue in the module [DataTypeRdf](https://github.com/Daniel-KM/Omeka-S-module-DataTypeRdf), that is fixed in version 3.3.4.2.
